#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

ps aux | grep 4-to_infinity_and_beyond | grep -v grep | awk '{print $2}' |xargs -I {} sh -c 'echo {} > /proc/{}/task/{}/children'

