#!/usr/bin/env bash
# This script displays PID and process name of bash processes

for pid in /proc/[0-9]*; do 
    pid=${pid##*/}
    if [ -r "/proc/$pid/comm" ]; then 
        name=$(cat "/proc/$pid/comm")
        if [ "$name" = "bash" ]; then
            echo "$pid bash"
        fi 
     fi
done


